# name: RandomEdits
# version: 1.0.5
# CubKit build info:
# CubKit source sha256: 3a96b0ae93999767d768a55d600b399f341669e04b57cf332c3886d6411e8c41
# CubKit payload sha256: d5b8d1c5ec30a8e90e3c594e0182608f9f28716e44f2d99f33a1e9a3d865643c
# CubKit source map:
# - generated line 116 -> RandomEdits.py:1
# - bundled files are extracted from the CubKit payload at import time:
#   - assets/strings_random_media.yaml -> strings_random_media.yaml:1 (lines: 39, sha256: f15e328c750c13fe67841c2e20a0fdf3d41c9505dd21b2ef72e596065f47b912)
#   - randomedits_lib/__init__.py -> __init__.py:1 (lines: 7, sha256: 84caae2083115d4732ebfb055b7f2d73c56da5bdac12f0677d28c86c887a3e9c)
#   - randomedits_lib/utils_mixin.py -> utils_mixin.py:1 (lines: 68, sha256: 1e566b1331999637b558d0f8957571e104393ffbdbf4ee9247e05603d41f9cad)

from __future__ import annotations
# Generated by CubKit. Do not edit this header by hand.
# CubKit repository: https://github.com/hairpin01/CubKit
# CubKit build notes:
# - Metadata comments above were generated/normalized from cubkit.toml and entrypoint code.
# - Bundled helper files are stored below as a base85-encoded zip payload.
# - On import, CubKit verifies the payload SHA256 and extracts it into CUBKIT_CACHE_DIR or ~/.cache/cubkit.
# - CubKit import-debug comments below explain sys.path/package wiring for private relative imports.
__cubkit_module_id__ = 'randomedits'
__cubkit_package_dirs__ = ('randomedits_lib',)
__cubkit_bundle_sha256__ = 'd5b8d1c5ec30a8e90e3c594e0182608f9f28716e44f2d99f33a1e9a3d865643c'
__cubkit_bundle_b85__ = """
P)h>@6aWAK2mk;8Appk0ZB|eO0090A001BW003cgb7gdMFLQKqX>Mn8Uvgn?WN&R>ZDnL>VJ>-
LZEU?&&2HO95WeRr2EN1rVwpc8DY>dH?V&ximpW&IBG(ctYF8yGt412Ywh$yioEk+8q&4aW0ea}EP*f?FY)gHG<tyX`+DGW@lA`3
qb_zrZWYA0Q?94acd@~!g)@}gQ$@WHQH<~`#@V$l?t-($Hf}ipUKa2Opf8c-
fNxaL?_<;BMm=ELofUgt$y^J5>NBqP`fTmqscG0ejN8%lM=$v=sJzNiYPp<Zpts(GU{FuK)n;ky5nZj^tHl@TD2>#?Je1Lmn^grU
~x8cjr0iB%T$#@rkk8yb_0*%EZ3%!EqcH=#C`#{1vh4=}A9*R%A2g{gKCw>q=<O6YX0214T|CM07C4e+Nr;Z3pQFVnh*tZ_Y=Zfc
kx@6=vOII~bS1i*~bSqy}m&*S>|NXGEI<+oCsZ!=Y$B*KU<PBX<ct76H<#MIfN?8P;Y@^A-D7-
3&rYc24Gj!FoOhd^Vs<l*peZ2o>jAH@6gUJcTk!nG$;9!Kg4wKmZ_`ZA|V3~%(Jmn&T;xbCEgrS(GVkrex*YiciENBYC`1SCg;lZ
0oUL>rF*nEtY8D)V0f$hnHcd`CLKx2?~dBq1Ah>%2)N2|!k4=eZza48%;uUe{+xAa0mD;mg-fOGWAC2)?hn7e6VM<@*><6P3vL7W
F`B5V={ZI7nHk)NUDFqf3?raHV=T9xma^;3~3iguW&Zl+)ia>0RYq`Bi2+np2l`&2yxEcJ^lPh_qgthXdLZIO;_i4$R*81~X`nq;
&$0~Qe{BJTCPYgS$<7K^548b(1ii&|dbdiFN&>%=G3z;1vHD{4LvN)$+i7JITQ5duo($BVi+#a@Y@$QH$JnRRS8H>;Ib=Ff3ojuj
j`9WihQ*kwO~baDc(cMd^r^hMmXIC2je=*K&_BU*7Z-
vpj;zUede4i5C9VG7MzX2DW5UDFNG_D6qQ(g^7Jp&Xv)LUrRbrHqn^9Gt!D6GIzu5C<k;SBbg}Fu}VaaTs;Odt!gUPp9~Urn5nUf
CcZVtltp$5cMpk>a>;@L@k3%MJ*K6qIJsJbRp4knqkVX5J6um95o&v2$^J{uETPJ&?~O8FIXEIHr<ARID|%!b|ExK7}`}5Ld0OpB
W-Bc2*pw4V@u#LdizGY6Ow@14I*zM7J%>3x;Pxw2!yN^I3)AUHsx31dQk|=6&!CQz^NZebJlWdi@Ik*Vh2tQ;V%4k`I<r4@*=z9C
wV}d1Ozr&i@LWl-5}Ur>>U!-
yf6v$$*m7{F?_|`7N(PVoxcb^OY8hUZh>#4z`!NVsP=J&ehLndq87EcY|oc<K@oa%%l19@!_V}J&zw4OQ2{~Q4qW69W+hu&hWUB6
9&CeMwLL0lvW>#8q5cyUdA<)7lJ*&K7e9m78JqU|cP)Z_kh>fj{>=s|E*3mZGvX3oA8U-
>q2&9fWcJ;G{{v7<0|XQR000O8001EXe!vl5W&i*HbN~PV8vp<Ra$#;{Z*65{X>@a6Y-wUIUtei%X>?y-E^v8G$uSOtFbqcF-KY5
Fg#~egF71rO!c<jOR6=W!G*MzIjt^|S?dfCYq3GY4M|SVUeLUt=U|+51ALAV{O>6KSGZW1vMRcoas1kM4A2jAv4AP%Bo<JnxLJ+|
XPr^}i(Wa#r?NCbt1QY-
O00;m803iTun*$8y0ssJc2mk;c0001TVQyq^ZDnL>baP*9X<{#RbZKmJUu|i4X>KlXd9_wekJ>O0z2{e0xoje(puI+-
YA?ODr}l)9<qZ?C*0Cdd*oCS;zT=OOgn-mNG#A3mcs|~HV`#1E80YN?PZl_5vg?gSCbTvvP#W#Bto1Q?>7_ml{;&EH%~t3=eI#>p
G_rv#Ym{(~@$d31^)Hml)mg^q*+a{?HntN={s!J0sSc>Zfod!ECe#UPpSon9J~M~54u|}cBH6~9ixA0-
WqDq%$RPWoyoR=9?=7_Q%%o;TenjkDy<X$0gLPi9V3>Z7FXdRwKe8QaQUPJny-Pe6G4D<2yua(IUP(*`D%Oc}Fl?U7?elJN{KbNJ
y;?008G2IR516mNu)K^g3U|>>1hX+pL4&+E4qX5;fTyIxEg`wP3n4|V9?-CAjBe#&n<rzw8<7Q#5-
*fMybFmj%_~^nW1}Q_R|h~Iql$EXJl%nF;sCB5o1;|QU3QI#V|o5McktxhsUQ(7A5s-
FAY<WbW>c~w&}V}=(e(;=@Z`HOd?^5$Mj*+Jx*?f}#;*ej=7-
U6PXdPO>l4fz2xp`zi+QTl|B&mEl2aSBiOU3gDW=DLoqz3VKyM}b9`xR)EVEnj4M7XRIXc4Q)(6q0<t4h2%Y9hiijwr|!qL>kBC<
cBPl6$~OY+1MQLue6Mpb^HQ^Z89LC$lf-AH|eDM1v>a|qHb--L2d#Vj6UeQ-stO-
z(eX7`4$!u}R3f_p5}h~5i;`~w$0;69uFWg>hc>)x>mhuL(R;F(YIaN`0UtyEClyOTU6)xzP!H=)SVm!{mL&t<?s?PhpchV;TZ;G
NmShA!Jq<@1oqg+jc1WX^>22Sy!83mf)-hPmCGpY{Zi)y3`*<jCpg1Wzul4ZP8CX=(fp*M1$sijb+EisC3-
P)|5P^6|Oyl76W7G^A4Eg(MJsEAJ`qE<!|ij4FJ|YB^$gJJW;~q1`)N+jy8D<D9ypKNNJuhip%ie*;h1F8d2mO928D0~7!N00;m8
03iUz!fjSi1ONd33jhEh00000000000001_0RR910AX`;Wpr~db98cPZfA2}a$#;{Z*5;~Wn^h#E_q>XY*0%90u%!j000080000X
0Diy`UuFOR0CWHV02=@R00000000000Hgtq1ONbXVQyq^ZDnL>baP*9X<{#5UukY>bYEXCaCuNm0Rj{Q6aWAK2mk;8ApmTf0}SQ@
004Oi0015U0000000000005)`Ed>Aoa$#;{Z*65{X>@a6Y-wUIb#!TLb6;&~cxi4faCuNm1qJ{B000930|4Uy002)200000
"""

def __cubkit_bootstrap__():
    # CubKit import-debug: this function is generated by CubKit.
    # It prepares bundled files before the real MCUB module code below runs.
    import base64
    import hashlib
    import os
    import sys
    import zipfile
    from pathlib import Path

    # CubKit import-debug: decode the embedded base85 zip payload.
    data = base64.b85decode("".join(__cubkit_bundle_b85__.split()).encode("ascii"))
    digest = hashlib.sha256(data).hexdigest()
    # CubKit import-debug: fail fast if the embedded payload was corrupted.
    if digest != __cubkit_bundle_sha256__:
        raise RuntimeError("CubKit embedded bundle checksum mismatch")

    # CubKit import-debug: cache extraction avoids rewriting helper files on every import.
    cache_root = Path(os.environ.get("CUBKIT_CACHE_DIR", Path.home() / ".cache" / "cubkit"))
    bundle_dir = cache_root / __cubkit_module_id__ / digest
    marker = bundle_dir / ".cubkit-extracted"
    if not marker.exists():
        bundle_dir.mkdir(parents=True, exist_ok=True)
        archive_path = bundle_dir / "bundle.zip"
        archive_path.write_bytes(data)
        with zipfile.ZipFile(archive_path) as archive:
            archive.extractall(bundle_dir)
        marker.write_text(digest, encoding="utf-8")

    # CubKit import-debug: expose extracted top-level files for normal absolute imports.
    bundle_path = str(bundle_dir)
    if bundle_path not in sys.path:
        sys.path.insert(0, bundle_path)

    # CubKit import-debug: build private package search paths for `from .utils import ...`.
    relative_import_paths = [bundle_path]
    for package_dir in reversed(__cubkit_package_dirs__):
        package_path = bundle_dir / package_dir
        if package_path.is_dir():
            relative_import_paths.insert(0, str(package_path))

    # CubKit import-debug: mark the generated main module as package-like.
    # This prevents accidental imports from global MCUB packages named `utils`, `lib`, etc.
    module_globals = globals()
    module_globals["__path__"] = relative_import_paths
    module_globals["__package__"] = module_globals.get("__name__", __cubkit_module_id__)
    module_spec = module_globals.get("__spec__")
    if module_spec is not None:
        module_spec.submodule_search_locations = relative_import_paths

__cubkit_bootstrap__()
del __cubkit_bootstrap__

# ---- CubKit entrypoint: RandomEdits.py ----
# scop: kernel min v1.4.5

import html
from pathlib import Path
import yaml
from telethon import events
from telethon.errors import (
    ChannelInvalidError,
    ChannelPrivateError,
    FloodWaitError,
    RPCError,
)
import asyncio

from core.lib.loader.module_base import ModuleBase, command
from core.lib.loader.module_config import ConfigValue, EntityLike, Integer, ModuleConfig, Row

# Local imports
from randomedits_lib import _MixinUtils

def _load_strings() -> dict[str, dict[str, str]]:
    for root in (Path(__file__).resolve().parent, *(Path(path) for path in globals().get("__path__", ()))):
        path = root / "assets" / "strings_random_media.yaml"
        if path.is_file():
            with path.open("r", encoding="utf-8") as file:
                return yaml.safe_load(file)

    raise FileNotFoundError("assets/strings_random_media.yaml")

class RandomEdits(
    _MixinUtils,
    ModuleBase
    ):

    name = "RandomEdits"
    version = "1.0.5"
    author = "@modulesanhedonuya && porting by @Hairpin00"
    description = {
        "ru": "Отправляет случайный эдит",
        "en": "Sends a random edit",
    }

    strings: dict[str, dict[str, str]] = _load_strings()

    config = ModuleConfig(
        ConfigValue(
            "channel",
            "randomeditsforme",
            description=lambda mod: mod.strings('key_channel'),
            validator=EntityLike(),
        ),
        Row(),
        ConfigValue(
            "sample_limit",
            500,
            description=lambda mod: mod.strings('key_sample_limit'),
            validator=Integer(min=1, max=500),
        ),
    )

    async def on_load(self) -> None:
        await super().on_load()

    @command(
        "randomedit",
        doc={
            "ru": "отправить случайный эдит",
            "en": "send a random edit",
        },
    )
    async def cmd_randomedit(self, event: events.NewMessage.Event) -> None:
        status = await self._edit_status(event, self.strings("pick"))

        try:
            ok, error_text = await self._send_random_post(
                event.chat_id,
                reply_to=getattr(event, "reply_to_msg_id", None),
            )
            if not ok:
                await self._edit_status(status, error_text or self.strings("no_posts"))
                return

            await self._edit_status(status, self.strings("done"))
            await asyncio.sleep(3)
            await status.delete()
        except (ChannelPrivateError, ChannelInvalidError, ValueError) as exc:
            self.log.warning("RandomEdits source channel is unavailable: %s", exc)
            await self._edit_status(status, self.strings("bad_channel"))
        except FloodWaitError as exc:
            self.log.warning("RandomEdits hit Telegram flood wait: %s", exc)
            await self._edit_status(
                status,
                self.strings("flood").format(seconds=getattr(exc, "seconds", 0)),
            )
        except RPCError as exc:
            self.log.warning("RandomEdits Telegram RPC error: %s", exc)
            error_text = str(exc)
            lowered = error_text.lower()
            if "protected" in lowered or "forbidden" in lowered or "copy" in lowered:
                await self._edit_status(status, self.strings("protected"))
                return
            await self._edit_status(
                status,
                self.strings("rpc_error").format(error=html.escape(error_text)),
            )
        except Exception as exc:
            self.log.exception("Unexpected RandomEdits error")
            await self._edit_status(
                status,
                self.strings("unknown_error").format(error=html.escape(str(exc))),
            )
