# name: RandomEdits
# version: 1.0.4
# CubKit build info:
# CubKit source sha256: 3ea6e616bddd9c45a95d9d3fa8695ea59639a7436b21812f8d7702f1366e8db5
# CubKit payload sha256: a4708ec1712a65c9feafd9fae5cc6c913675e8be01b412d38643ae50c4cf61c0
# CubKit source map:
# - generated line 119 -> RandomEdits.py:1
# - bundled files are extracted from the CubKit payload at import time:
#   - randomedits_lib/__init__.py -> __init__.py:1 (lines: 9, sha256: 805780d0ce735f8c06faa2affa008d8325bcf078d46c65aead82cc209bccfd3c)
#   - randomedits_lib/strings.py -> strings.py:1 (lines: 53, sha256: 31cadf8543bbee4f407e68e19f3d951eb753a69a2e78f0b55e83a9a2dc89595d)
#   - randomedits_lib/utils_mixin.py -> utils_mixin.py:1 (lines: 68, sha256: 1e566b1331999637b558d0f8957571e104393ffbdbf4ee9247e05603d41f9cad)

from __future__ import annotations
# Generated by CubKit. Do not edit this header by hand.
# CubKit repository: https://github.com/hairpin01/CubKit
# CubKit build notes:
# - Metadata comments above were generated/normalized from cubkit.toml and entrypoint code.
# - Bundled helper files are stored below as a base85-encoded zip payload.
# - On import, CubKit verifies the payload SHA256 and extracts it into CUBKIT_CACHE_DIR or ~/.cache/cubkit.
# - CubKit import-debug comments below explain sys.path/package wiring for private relative imports.
__cubkit_module_id__ = 'randomedits'
__cubkit_package_dirs__ = ('randomedits_lib',)
__cubkit_bundle_sha256__ = 'a4708ec1712a65c9feafd9fae5cc6c913675e8be01b412d38643ae50c4cf61c0'
__cubkit_bundle_b85__ = """
P)h>@6aWAK2mk;8App>*!{2=X005u>000{R0044fZe(w5Wn^h|b6;#}VlQ7`X>MtBUtcb8c~eqS3Mk4fODsuMC`e4sPE1c#NXsu$
D9OkyR`7KWbyCR9Pbtkw)l*VZ;^Imx%Fk8MD=sO@%u6p;$jmLsFDg+84hiz~a}S0}mX>7Z6vyXgR%GVE6vX?2c%dK(F0T0a#GIV?
cm-R9Xf6dHP={()*MV@66a$4~xd2d00|XQR000O8001EX^nhwz)&l?lJ`4Z=8UO$Qa$#;{Z*65{X>@a6Y-
wUIb98cPZfA2YaCya7-EJF26u$RUjP}N@)F%7m-
Sr07HwYmv=tUE*D6+=hX}n}TV`kS4Q4}e}LJ*M>AtC`0p+e$<%f#5Nlhn>D%)CNh03Lxe<G-
YiA*j@~65G3TcFuRc?>lGYOlEoI!3X!>Uq<)PW(L8_;0<GG_+4L9TqAJDcz|ihYVU<nnizK`%k`+T2Fuw(x_Xz?*ryTF?{}l{p5f
+f-?41lF@4WB9X}UXM)9wwza117N6|%8C>O<#a#uEyxDb8u2mH6?-
onB{VX<7yUdlvSsm>C}J}aATnSpD&j^+8DYvx?bH;ONh_FhePBsxeoMOz$;bJ3Sy$UP)_aB(VkM0Wt9Ex*+7`*K%wRrnJK@5-
GiOd+FWHXhUSOyA5~j*|;aFK?TG=jVezyZf&~`c<6Eru<5Q5Iy;gI2~t1fN)1#$Zc3_0p5=2DYRYjOmwEuBqU8Ex~dquHNLA}*W+
_?mT$Q^-
^u6gzy;nEzQdoc!FME%fu|in(FcTQil!Hupe6v{Us5<8((IL#hI;N0P%CQBbqFd{SV)SSl`5u`#9M_$ef^Lc(@%b{7!fB>C_Ilu3
rINuDz;VfE1ShpElNjQO*XoHiIy@BOT(P6>z#2yN`wwb)YrT;!8KZ$E=bf>?mB~@=PGy**b*JU-
V^;P&FY+`q>_^GhN9Vi&J2RUvpv_%TV7!26wn{0MOz^;S>?EfG!EsUjxxA{t}Nby3&m#-
jQ8zTmz_Z`$|q`Fb>rBI;&|bDp`)UB3b7a39w$)zDS}+P@;jtAe2!jjA0WNZRv3nA>NTLJEw^Dswf*VkK8t3E`6y=Wrd&CJ>nUUV
Uf#EC$97ybehz=Xru`u6*C1M7yinHe4ND(W2Qn+pZcYHit4&&9Ug&Ejeg}xyOh|>%FxgV;9dY&#b@F<pL^x;sbuIe~6xN020Y{>d
C$4mm&NAwt%hqhrHOkiM{{sW2F7WXTptN-lK^Mt=<-
0Mue+9KQ_%H~a`w5j0%qvxxt#9sJy3bJ3h*DgR2_jGfS|^;KN321^J1AkCZ@i(?C#^=wAmcl?=XRug$ifB`I@*5b5%TU}ZvWTwV;
R@#uzg7CY4z<L7env}_-
#=97)P;ImvI!)$2g9{w{RMiV^&!sAsCCVV;%zeXkvh+TWHpVTj3iBui}X6X^tsNtAr1Y8pSaxD=}k@eZJFsg)vmabOUknS%W|y&K
%N{65ww#is8!~=I~emz1jQ+@JEz<Uf1&65CKfvtxP6UD&aUTmEiZm$NF}5_=6#v`6Tl<P)h>@6aWAK2mk;8ApmTf0}SQ@004Oi00
15U0044fZe(w5Wn^h|b6;#}VlQ=cX>4;}ZE1LEZZ2?nwN_1!+At8k=T}&{Y$Bzgy+)#HFTJ&=_Jok-
4HK}|u_Jrfg{nWk<ByPpfYd!S7sAYVKHhs{XsziO=j{nk7C2|J>y1Swv^FSE8tt;I^)Yzqr9KS)ulf?rR_Hx_By)2#vVkmXlyHvm
@A545FO<sFS;pwuL(8}}wi8PJ2HqU04yeL`YAg08)Cp>zx@4a|Gl#Yghy0Tw*~XiT5Xp>Xd0wu_Ap4@chPGtyEwu8?q-
I5aMC@I?UgN5RbzZSxn0}8h<yg!=vK?wt0b$X-
OFR}a?@j2uzw4=9NlXVS)`@d4Y@W;Q^KNnc#e#UfS}hP6dQ#sHn6JOEyo@jkchOA*voT6RgS<BmT>vtGr=-IzA-
TH?Aw{ho(6DNZZslQ{Cu6=Fkp+zsFO)#M3yCq!D_GxSqa=A(2S6U9igbQF-GOuB0InXJqg2~nc8!Q*dHy<g@Z{a8AQ3DdQWY~GW8
rFMQ?et_XM;J>^$K|K<hwC^DFB*AAjyroA(@EAuLB9@htY6P0*31A6U-
b4XQU~Md8*X^kn53>Qya92%LIEVrpJAqf9+{NZzcL3^xmf|vs>{EK?}h-
I>O`D2hpYFCAyKzeOTX$lJx4r(bU8uvOl3uf+4m`^28HSuzfK`ReqsU#6+w?&U2;RNPUDUK@`k$2+}OygmO^DEFNQha7C_7Oq5S%
_lB^-{uV2Odo0t4-V1>I0~bEvKAZk!B77q2-
mwXX*>sxVnNRX?;{qM6R8ZWzlRPEW!r{X=p~%vgrre~@Wxzn~W_VeK^ujveo!P^NF56D!^N`7fLcDxr&V=*_Mjc2C8}@&Ox!s(f_
5_jD#qJQ~$m!<<PcE$uywPxJY5We?ejUP!kg1-E;wW5DPdGvH@wxJneyH~}q*CIABoKTn?<wytLPU3rDtyUmIbwM`(}WhG-
8)>{c$gsLoVubv6m-
RhY)_Ma15ep5`wLJ@0Rj{Q6aWAK2mk;8App>*!{2=X005u>000{R0000000000005)`00000a$#;{Z*65{X>@a6Y-
wUIUtei%X>?y-
E^v8JO928D0~7!N00;m803iVMfNEXV0{{R%3;+Nc00000000000001_0k!}D0CHh&WN&R{WNCDBUu<b&FLQKqX>Mn8E^v8JO928D
0~7!N00;m803iTun*$8y0ssJc2mk;c00000000000001_0mK9V0CHh&WN&R{WNCDBUu<b&FLiWjY;#|2X?SUFE^v8JO9ci100003
00RKs0002y2LJ#700
"""

def __cubkit_bootstrap__():
    # CubKit import-debug: this function is generated by CubKit.
    # It prepares bundled files before the real MCUB module code below runs.
    import base64
    import hashlib
    import os
    import sys
    import zipfile
    from pathlib import Path

    # CubKit import-debug: decode the embedded base85 zip payload.
    data = base64.b85decode("".join(__cubkit_bundle_b85__.split()).encode("ascii"))
    digest = hashlib.sha256(data).hexdigest()
    # CubKit import-debug: fail fast if the embedded payload was corrupted.
    if digest != __cubkit_bundle_sha256__:
        raise RuntimeError("CubKit embedded bundle checksum mismatch")

    # CubKit import-debug: cache extraction avoids rewriting helper files on every import.
    cache_root = Path(os.environ.get("CUBKIT_CACHE_DIR", Path.home() / ".cache" / "cubkit"))
    bundle_dir = cache_root / __cubkit_module_id__ / digest
    marker = bundle_dir / ".cubkit-extracted"
    if not marker.exists():
        bundle_dir.mkdir(parents=True, exist_ok=True)
        archive_path = bundle_dir / "bundle.zip"
        archive_path.write_bytes(data)
        with zipfile.ZipFile(archive_path) as archive:
            archive.extractall(bundle_dir)
        marker.write_text(digest, encoding="utf-8")

    # CubKit import-debug: expose extracted top-level files for normal absolute imports.
    bundle_path = str(bundle_dir)
    if bundle_path not in sys.path:
        sys.path.insert(0, bundle_path)

    # CubKit import-debug: build private package search paths for `from .utils import ...`.
    relative_import_paths = [bundle_path]
    for package_dir in reversed(__cubkit_package_dirs__):
        package_path = bundle_dir / package_dir
        if package_path.is_dir():
            relative_import_paths.insert(0, str(package_path))

    # CubKit import-debug: mark the generated main module as package-like.
    # This prevents accidental imports from global MCUB packages named `utils`, `lib`, etc.
    module_globals = globals()
    module_globals["__path__"] = relative_import_paths
    module_globals["__package__"] = module_globals.get("__name__", __cubkit_module_id__)
    module_spec = module_globals.get("__spec__")
    if module_spec is not None:
        module_spec.submodule_search_locations = relative_import_paths

__cubkit_bootstrap__()
del __cubkit_bootstrap__

# ---- CubKit entrypoint: RandomEdits.py ----
# scop: kernel min v1.4.5

import html

from typing import Any

from telethon import events
from telethon.errors import (
    ChannelInvalidError,
    ChannelPrivateError,
    FloodWaitError,
    RPCError,
)

from core.lib.loader.module_base import ModuleBase, command
from core.lib.loader.module_config import ConfigValue, EntityLike, Integer, ModuleConfig, Row

# Local imports
from randomedits_lib import STRINGS
from randomedits_lib import _MixinUtils

class RandomEdits(_MixinUtils, ModuleBase):
    """Отправляет случайный эдит."""

    name = "RandomEdits"
    version = "1.0.4"
    author = "@modulesanhedonuya && porting by @Hairpin00"
    description = {
        "ru": "Отправляет случайный эдит",
        "en": "Sends a random edit",
    }

    strings = STRINGS

    config = ModuleConfig(
        ConfigValue(
            "channel",
            "randomeditsforme",
            description="Юзернейм, ID или ссылка на канал-источник эдитов(лучше не трогать)",
            validator=EntityLike(),
        ),
        Row(),
        ConfigValue(
            "sample_limit",
            500,
            description="Сколько последних сообщений канала просматривать при выборе",
            validator=Integer(min=1, max=500),
        ),
    )

    async def on_load(self) -> None:
        await super().on_load()

    @command(
        "randomedit",
        doc={
            "ru": "отправить случайный эдит",
            "en": "send a random edit",
        },
    )
    async def cmd_randomedit(self, event: events.NewMessage.Event) -> None:
        status = await self._edit_status(event, self.strings("pick"))

        try:
            ok, error_text = await self._send_random_post(
                event.chat_id,
                reply_to=getattr(event, "reply_to_msg_id", None),
            )
            if not ok:
                await self._edit_status(status, error_text or self.strings("no_posts"))
                return

            await self._edit_status(status, self.strings("done"))
        except (ChannelPrivateError, ChannelInvalidError, ValueError) as exc:
            self.log.warning("RandomEdits source channel is unavailable: %s", exc)
            await self._edit_status(status, self.strings("bad_channel"))
        except FloodWaitError as exc:
            self.log.warning("RandomEdits hit Telegram flood wait: %s", exc)
            await self._edit_status(
                status,
                self.strings("flood").format(seconds=getattr(exc, "seconds", 0)),
            )
        except RPCError as exc:
            self.log.warning("RandomEdits Telegram RPC error: %s", exc)
            error_text = str(exc)
            lowered = error_text.lower()
            if "protected" in lowered or "forbidden" in lowered or "copy" in lowered:
                await self._edit_status(status, self.strings("protected"))
                return
            await self._edit_status(
                status,
                self.strings("rpc_error").format(error=html.escape(error_text)),
            )
        except Exception as exc:
            self.log.exception("Unexpected RandomEdits error")
            await self._edit_status(
                status,
                self.strings("unknown_error").format(error=html.escape(str(exc))),
            )
